# Generated by Django 4.1 on 2022-07-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pouser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
