# Generated by Django 4.1 on 2022-07-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchout', '0002_pouser_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='pouser',
            name='apellido',
            field=models.CharField(default='probas', max_length=100),
        ),
        migrations.AddField(
            model_name='pouser',
            name='businessunit',
            field=models.CharField(default='probas', max_length=100),
        ),
        migrations.AddField(
            model_name='pouser',
            name='buyercookie',
            field=models.CharField(default='probas', max_length=100),
        ),
        migrations.AddField(
            model_name='pouser',
            name='email',
            field=models.CharField(default='probas', max_length=100),
        ),
        migrations.AddField(
            model_name='pouser',
            name='nombre_unico',
            field=models.CharField(default='probas', max_length=100),
        ),
        migrations.AddField(
            model_name='pouser',
            name='user',
            field=models.CharField(default='probas', max_length=100),
        ),
        migrations.AlterField(
            model_name='pouser',
            name='nombre',
            field=models.CharField(default='probas', max_length=100),
        ),
    ]
