# Generated by Django 4.1 on 2022-07-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchout', '0003_pouser_apellido_pouser_businessunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pouser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
