# Generated by Django 4.1 on 2022-07-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchout', '0004_alter_pouser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pouser',
            name='url',
            field=models.CharField(default='probas', max_length=100),
        ),
    ]
