# Generated by Django 4.1 on 2022-07-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchout', '0005_pouser_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pouser',
            old_name='url',
            new_name='secretID',
        ),
        migrations.AddField(
            model_name='pouser',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pouser',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pouser',
            name='urlToRedirect',
            field=models.CharField(default='probas', max_length=100),
        ),
    ]
