# Generated by Django 4.1 on 2022-07-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchout', '0006_rename_url_pouser_secretid_pouser_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pouser',
            name='sessionExpiredAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pouser',
            name='sessionOpen',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pouser',
            name='totalSessions',
            field=models.IntegerField(null=True),
        ),
    ]
